/*
    CHAOS REALM — PresetManager.cpp
*/
#include "PresetManager.h"

// Generated by juce_add_binary_data(CHAOSRealmData SOURCES presets/FactoryPresets.xml)
#include "BinaryData.h"

PresetManager::PresetManager (juce::AudioProcessorValueTreeState& state) : apvts (state)
{
    loadFromBinaryData();
}

void PresetManager::loadFromBinaryData()
{
    presets.clear();

    // BinaryData::FactoryPresets_xml is emitted from presets/FactoryPresets.xml
    // by juce_add_binary_data(CHAOSRealmData ...).
    const char* data = BinaryData::FactoryPresets_xml;
    const int   size = BinaryData::FactoryPresets_xmlSize;
    if (data == nullptr || size <= 0) return;

    auto root = juce::XmlDocument::parse (juce::String::fromUTF8 (data, size));
    if (root == nullptr) return;

    for (auto* preset : root->getChildWithTagNameIterator ("Preset"))
    {
        Entry e;
        e.category = preset->getStringAttribute ("category");
        e.name     = preset->getStringAttribute ("name");
        e.xml      = std::make_unique<juce::XmlElement> (*preset);
        presets.push_back (std::move (e));
    }
}

void PresetManager::loadPreset (int i)
{
    if (! isValid (i)) return;
    current = i;

    for (auto* p : presets[(size_t) i].xml->getChildWithTagNameIterator ("P"))
    {
        const auto id  = p->getStringAttribute ("id");
        const auto val = (float) p->getDoubleAttribute ("v");
        if (auto* param = apvts.getParameter (id))
            param->setValueNotifyingHost (param->convertTo0to1 (val));
    }
}
